### ISSUE TITLE
Rebuild for PyTorch 1.12

### ISSUE THREAD

**Issue by raimis** [conda-forge/nnpops-feedstock#9]
### Comment:

A bot has rebuilt OpenMM-Torch for PyTorch 1.12 (https://github.com/conda-forge/openmm-torch-feedstock/pull/24). Why the same has not happened with NNPOps?

Ping @mikemhenry @hmaarrfk

**Comment by hmaarrfk** [comment]
It requires torachani first.

See the migration status
https://conda-forge.org/status/#other_migrations

browse down to pytorch

**Comment by raimis** [comment]
@hmaarrfk thanks! I wasn't aware of that page.

Let's wait until @mikemhenry finishes https://github.com/conda-forge/torchani-feedstock/pull/12

**Comment by mikemhenry** [comment]
Yes! Sorry, for some really weird reason the tag showed up on my phone but not the website UI for notifications. 
Just so I can prioritize, this is a blocker for the big openmm 8.0 "Machine Learning" release, right? Or is it okay if we don't have PyTorch 1.12 support on release day?

**Comment by raimis** [comment]
This isn't a blocker for OpenMM 8.

**Comment by davkovacs** [comment]
What is the current status of this?

**Comment by mikemhenry** [comment]
I think it has been rebuilt for 1.12:
https://github.com/conda-forge/nnpops-feedstock/pull/10

**Comment by mikemhenry** [comment]
Let me know if this issues needs to be opened @davkovacs
